// <auto-generated />
using GreenThumb2._0.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreenThumb2._0.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231207122222_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GreenThumb2._0.Models.InstructionModel", b =>
                {
                    b.Property<int>("InstructionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstructionId"));

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.HasKey("InstructionId");

                    b.HasIndex("PlantId");

                    b.ToTable("Instructions");

                    b.HasData(
                        new
                        {
                            InstructionId = 1,
                            Instructions = "Vattna regelbundet",
                            PlantId = 1
                        },
                        new
                        {
                            InstructionId = 2,
                            Instructions = "Undvik direkt solljus",
                            PlantId = 1
                        },
                        new
                        {
                            InstructionId = 3,
                            Instructions = "Vattna sparsamt",
                            PlantId = 2
                        },
                        new
                        {
                            InstructionId = 4,
                            Instructions = "Placera i soligt fönster",
                            PlantId = 3
                        },
                        new
                        {
                            InstructionId = 5,
                            Instructions = "Beskär efter blomning",
                            PlantId = 4
                        },
                        new
                        {
                            InstructionId = 6,
                            Instructions = "Skydda från frost",
                            PlantId = 5
                        },
                        new
                        {
                            InstructionId = 7,
                            Instructions = "Väldränerad jord rekommenderas",
                            PlantId = 6
                        },
                        new
                        {
                            InstructionId = 8,
                            Instructions = "Använd orkidéjord",
                            PlantId = 7
                        },
                        new
                        {
                            InstructionId = 9,
                            Instructions = "Skydda från stark vind",
                            PlantId = 8
                        },
                        new
                        {
                            InstructionId = 10,
                            Instructions = "Kräver minimalt med vatten",
                            PlantId = 9
                        },
                        new
                        {
                            InstructionId = 11,
                            Instructions = "Växer bäst i halvskugga",
                            PlantId = 10
                        },
                        new
                        {
                            InstructionId = 12,
                            Instructions = "Gödsla måttligt",
                            PlantId = 3
                        });
                });

            modelBuilder.Entity("GreenThumb2._0.Models.PlantModel", b =>
                {
                    b.Property<int>("PlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlantId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlantId");

                    b.ToTable("Plants");

                    b.HasData(
                        new
                        {
                            PlantId = 1,
                            Name = "Ormbunke"
                        },
                        new
                        {
                            PlantId = 2,
                            Name = "Ros"
                        },
                        new
                        {
                            PlantId = 3,
                            Name = "Kaktus"
                        },
                        new
                        {
                            PlantId = 4,
                            Name = "Lavendel"
                        },
                        new
                        {
                            PlantId = 5,
                            Name = "Tulpan"
                        },
                        new
                        {
                            PlantId = 6,
                            Name = "Solros"
                        },
                        new
                        {
                            PlantId = 7,
                            Name = "Orkidé"
                        },
                        new
                        {
                            PlantId = 8,
                            Name = "Körsbärsblom"
                        },
                        new
                        {
                            PlantId = 9,
                            Name = "Lilja"
                        },
                        new
                        {
                            PlantId = 10,
                            Name = "Vitsippa"
                        });
                });

            modelBuilder.Entity("GreenThumb2._0.Models.InstructionModel", b =>
                {
                    b.HasOne("GreenThumb2._0.Models.PlantModel", "Plant")
                        .WithMany("Instructions")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("GreenThumb2._0.Models.PlantModel", b =>
                {
                    b.Navigation("Instructions");
                });
#pragma warning restore 612, 618
        }
    }
}
